const numberButton = document.querySelectorAll(['data-number'])
const operationButton = document.querySelectorAll(['data-operation'])
const deleteButton = document.querySelector(['data-delete'])
const equalsButton = document.querySelector(['data-equals'])
const deleteButton = document.querySelector(['data-delete'])
const allClearButton = document.querySelector(['data-all-clear'])
const currentOperandTextElement = document.querySelector(['data-current-operand'])
const previousOperandTextElement = document.querySelector(['data-previous-operand'])